import type { ReactNode } from 'react'

export interface Message {
  id: string
  role: 'user' | 'assistant'
  content: string
  agentId?: string // Identificador do robô que enviou a mensagem
  imageUrl?: string
  imageGenerated?: string // Base64 image generated by AI
}

export interface Suggestion {
  icon: ReactNode
  title: string
  text: string
  prompt: string
}

export interface ApiResponse {
  response: string
  image_base64?: string
}

export interface Agent {
  id: string
  name: string
  description: string
  icon: string
}
